# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyilvantartas', '0002_auto_20160416_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='btype',
            field=models.CharField(choices=[('1m', '1 hónapos kölcsönzés'), ('1w', '1 hetes kölcsönzés'), ('0w', 'nem kölcsönözhető')], default='1m', max_length=2, verbose_name='type of lending'),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lending',
            name='lending_date',
            field=models.DateTimeField(),
        ),
    ]
